version: '2'  
services:  
  datastore-microservice:
    build: ./datastore-service
    container_name: datastore_service
    ports:
     - "8123:8123"
    links:
     - db:db
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./datastore-db
